version: 2.1

parameters:
  test-backend:
    type: boolean
    default: false

orbs:
  python: circleci/python@1.4.0

workflows:
  backend:
    when: << pipeline.parameters.test-backend >>
    jobs:
      - python/test:
          app-dir: backend
          pkg-manager: pipenv
          test-tool: pytest
          version: '3.9'
